### ISSUE TITLE
GitHub Action

### ISSUE THREAD

**Issue by pinkforest** [davidlattimore/cackle#1]
Would be nice to be able to run in CI ?

**Comment by davidlattimore** [comment]
I had been waiting until others were contributing to set up CI, since I push several commits per day and figured it would use a bit of resources to run on every commit. That said, it'll need CI at some point and maybe that time has come :)

**Comment by pinkforest** [comment]
ya I have one for you, I'll send a PR

**Comment by pinkforest** [comment]
PR's up 
- #2 :)
