### ISSUE TITLE
"Namespace missing name attribute" failure

### ISSUE THREAD

**Issue by repi** [davidlattimore/cackle#8]
Using latest [v0.1.1](https://github.com/davidlattimore/cackle/releases/tag/v0.1.1) released version runs fine on our project, but wanted to try out the latest version from git and when running that it aborts on this error:

```sh
$ cackle ui
Namespace missing name attribute
```

Saw that was introduced in 705c657323e46419202cb7fef40397fb44b805a6, so tested running the commit just before that 6328b157f33f0f37787ecbea49b78aec0e277152 and it works fine:

```sh
$ cackle ui
Completed successfully for configuration /home/repi/git/embark/ark/cackle.toml
num_packages: 897
no_special_permissions: 401
```

Any ideas if there is an issue with the parsing there or are there new requirements/configuration needed from that version? And let me know if there is any more information I can provide that would be of help!

**Comment by davidlattimore** [comment]
Thanks for noticing that! I guessed that it might be due to it encountering a C++ anonymous namespace and indeed was able to reproduce the problem. Just working on tests plus a fix...

**Comment by repi** [comment]
sweet thanks! can confirm e52eccfbaff92cc5e28e6586e12776673e9620c4 fixed this
